---
title: "Get peak flow data for Northwestern Great Plains ecoregion gages"
author: "CJ Tinant"
date: "`r Sys.Date()`"
output: html_document
---

<!--

-->

```{r 00_setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# library
library(tidyverse)        # Load the 'Tidyverse' packages: ggplot2, dplyr, 
                          #   tidyr, readr, purrr, tibble, stringr, and forcats
library(dataRetrieval)

```



```{r 01_find_sites_get_peak discharge}

# watermapper for visualization
# https://maps.waterdata.usgs.gov/mapper/index.html

#  west  south  east  north
# -111.5, 42.0, -99.5, 48.5

# get a list of sites for the Northwestern Great Plains ecoregion bounding box
sites_nw <- whatNWISsites(                       #  west  south  east  north
  bBox = c(-111.5, 45.0, -105.5, 48.5)           # -111.5, 45.0, -105.5, 48.5
  )

sites_sw <- whatNWISsites(                       #  west  south  east  north
  bBox = c(-111.5, 42.0, -105.5, 45.0)           # -111.5, 42.0, -105.5, 45.0
  )

sites_ne <- whatNWISsites(                       #  west  south  east  north
  bBox = c(-105.5, 45.0, -99.5, 48.5)            # -105.5, 45.0, -99.5, 48.5
  )

sites_se <- whatNWISsites(                       #  west  south  east  north
  bBox = c(-105.5, 42.0, -99.5, 45.0)            # -105.5, 42.0, -99.5, 45.0
  )

sites_st <- bind_rows(sites_nw, sites_sw, sites_ne, sites_se) 

# filter stream gages
sites_st <- sites_st %>%
  filter(site_tp_cd == "ST")

sites <- sites_st %>%
  select(site_no) 
  
# get a list of peak flow data greater than 20-years
sites_peak <-  whatNWISdata(
  siteNumber = sites$site_no,
  service = "pk"
  )
  
sites_peak_gt_20 <- sites_peak %>%
  filter(count_nu > 20)

# download peak data
peakData <- readNWISpeak(siteNumbers)

```

START HERE
```{r 05_get_wcc_gage_ht_data_87_97}

# from email to USGS -- see correspondence file
gage_ht_87_97 <- read_csv("data/Gage_height.ft.Work.Mean.finl.ref@06445980.EntireRecord.csv",
                          skip = 14,
                          show_col_types = FALSE
                          ) %>%
  janitor::clean_names()

# check data
ck_grade <- gage_ht_87_97 %>%
  select(grade) %>%
  distinct()

ck_date <- gage_ht_87_97 %>%
  group_by(grade) %>%
  summarise(min_date = min(timestamp_utc_07_00),
            max_date = max(timestamp_utc_07_00),
            )

ck_ht <- gage_ht_87_97 %>%
  group_by(grade) %>%
  summarise(min_ht = min(value),
            max_ht = max(value),
            )

rm(list = ls(pattern = "ck_"))

```

```{r 06_get_wcc_gage_ht_data_97-99}

# from email to USGS -- see correspondence file
gage_ht_97_99 <- read_csv("data/Gage_height.ft.BY_DATA_LOGGER.Work.Mean@06445980.EntireRecord.csv",
                          skip = 14,
                          show_col_types = FALSE
                          ) %>%
  janitor::clean_names()

# check data
ck_grade <- gage_ht_97_99 %>%
  select(grade) %>%
  distinct()

ck_date <- gage_ht_97_99 %>%
  group_by(grade) %>%
  summarise(min_date = min(timestamp_utc_07_00),
            max_date = max(timestamp_utc_07_00),
            )

ck_ht <- gage_ht_97_99 %>%
  group_by(grade) %>%
  summarise(min_ht = min(value),
            max_ht = max(value),
            )

rm(list = ls(pattern = "ck_"))

```

```{r 07_compile_wcc_gage_ht_data)}

gage_ht_87_99 <- bind_rows(
  gage_ht_87_97,
  gage_ht_97_99
  )

rm(gage_ht_87_97,
  gage_ht_97_99
  )

```

```{r 08_make_metadata_data_peak_flow_vars, message=FALSE}

meta_peak_vars <- tibble::tribble(
       ~name,  ~type, ~description,
       "agency_cd", "character", "The NWIS code for the agency reporting the data",
        "site_no", "character", "The USGS site number",
       "peak_dt", "Date", "Date of peak streamflow",
       "peak_tm", "character", "Time of peak streamflow as character",
        "peak_va", "numeric", "Annual peak streamflow value in cfs",
        "peak_cd", "character", "Peak Discharge-Qualification codes (see comment for more information)",
       "gage_ht", "numeric", "Gage height for the associated peak streamflow in feet",
       "gage_ht_cd", "character", "Gage height qualification codes",
       "year_last_pk", "numeric", "Peak streamflow reported is the highest since this year",
       "ag_dt", "Date", "Date of maximum gage-height for water year (if not concurrent with peak)",
       "ag_tm", "character", "Time of maximum gage-height for water year (if not concurrent with peak)",
       "ag_gage_ht",   "numeric", "maximum Gage height for water year in feet (if not concurrent with peak)",
       "ag_gage_ht_cd", "character", "maximum Gage height code"
  )

```

```{r 09_make_metadata_peak_flow_codes, message=FALSE}

meta_peak_discharge_codes <-tibble::tribble(
  ~code, ~description,
  "1", "Discharge is a maximum daily average",
  "2", "Discharge is an estimate",
  "3", "Discharge affected by dam failure",
  "4", "Discharge less than indicated value, which is minimum recordable discharge at this site*",
  "5", "Discharge affected to unknown degree by regulation or diversion**",
  "6", "Discharge affected by regulation or diversion**",
  "7", "Discharge is an historic peak***",
  "8", "Discharge actually greater than indicated value",
  "9", "Discharge due to snowmelt, hurricane or debris dam breakup",
  "A", "Year of occurrence is unknown or not exact",
  "B", "Month or day of occurrence is unknown or not exact",
  "C", "All or part of the record affected by urbanization, mining, agricultural changes, channelization, or others",
  "D", "Base discharge changed during this year",
  "E", "Only the annual maximum peak exceeded base discharge this year",
  "*", "Code 4 cannot occur simultaneously with codes 1, 2, 3, 7, or 8.",
  "**", "Codes 5 and 6 cannot occur simultaneously.",
  "***", "Code 7 should indicate that the value for the particular year is an historic peak and the particular year occurred before or after the systematic record, or during a break in the systematic record")

```

```{r 09_make_metadata_peak_gate_ht_codes, message=FALSE}

meta_peak_gage_ht_codes <-tibble::tribble(
  ~code, ~description,
  "1", "Gage height affected by backwater",
  "2", "Gage height not the maximum for the year*",
  "3", "Gage height at different site and/or datum",
  "4", "Gage height below minimum recordable elevation",
  "5", "Gage height is an estimate",
  "6", "Gage datum changed during this year",
  "*", "If code 2 is given here, then a date and data entries should be made for the maximum annual gage height"
  )

```

```{r 10_make_metadata_NWIS_codes}

meta_NWIS_site_codes <- tibble::tribble(
  ~code, ~description,
  "agency_cd", "The NWIS code for the agency reporting the data",
  "site_no", "Site identification number",
  "station_nm", "Station name",
  "site_tp_cd", "Primary and secondary site-type code",
  "lat_va", "Latitude",
  "long_va", "Longitude",
  "dec_lat_va", "Latitude NAD83 (decimal degrees)",
  "dec_long_va", "Longitude NAD83 (decimal degrees)",
  "coord_meth_cd", "Lat/long method",
  "coord_acy_cd", "Lat/long accuracy",
  "coord_datum_cd", "",
  "dec_coord_datum_cd", "Lat/long datum",
  "district_cd", "District code",
  "state_cd", "State code",
  "county_cd", "County code",
  "country_cd", "Country code",
  "land_net_ds", "Land-net location",
  "map_nm", "Name of location map",
  "map_scale_fc", "Scale of location map",
  "alt_va", "Altitude of land surface",
  "alt_meth_cd", "Method altitude determined",
  "alt_acy_va", "Altitude accuracy code",
  "alt_datum_cd", "Altitude datum",
  "huc_cd", "Hydrologic unit code",
  "basin_cd", "Drainage basin code",
  "topo_cd", "Topographic setting code",
  "instruments_cd", "Flags-instruments at site",
  "construction_dt", "Date site established/inventoried",
  "inventory_dt", "Date of first construction",
  "drain_area_va", "Drainage area",
  "contrib_drain_area_va", "Contributing drainage area",
  "tz_cd", "Standard time zone code",
  "local_time_fg", "Local standard time flag",
  "reliability_cd", "Data Reliability code",
  "gw_file_cd", "Other types of ground-water data",
  "nat_aqfr_cd", "National aquifer code",
  "aqfr_cd", "Primary aquifer code",
  "aqfr_type_cd", "Aquifer-type code",
  "well_depth_va", "Well depth",
  "hole_depth_va", "Hole depth",
  "depth_src_cd", "Source-of-depth data",
  "project_no", "Project number"
)

```

```{r 11_make_metadata_NWIS_site_types}

# https://maps.waterdata.usgs.gov/mapper/help/sitetype.html
meta_NWIS_site_types <- tribble(
  ~site_type_code, ~site_type_name, ~site_type_description,                 "ES", "Estuary", "A coastal inlet of the sea or ocean; esp. the mouth of a river, where tide water normally mixes with stream water (modified, Webster). Salinity in estuaries typically ranges from 1 to 25 Practical Salinity Units (psu), as compared oceanic values around 35-psu. See also: tidal stream and coastal.",
  "LK", "Lake, Reservoir, Impoundment", "An inland body of standing fresh or saline water that is generally too deep to permit submerged aquatic vegetation to take root across the entire body (cf: wetland). This site type includes an expanded part of a river, a reservoir behind a dam, and a natural or excavated depression containing a water body without surface-water inlet and/or outlet.",
  "OC", "Ocean", "Site in the open ocean, gulf, or sea. (See also: Coastal, Estuary, and Tidal stream).",
  "OC-CO", "Coastal", "An oceanic site that is located off-shore beyond the tidal mixing zone (estuary) but close enough to the shore that the investigator considers the presence of the coast to be important. Coastal sites typically are within three nautical miles of the shore.",
  "ST", "Stream", "A body of running water moving under gravity flow in a defined channel. The channel may be entirely natural, or altered by engineering practices through straightening, dredging, and (or) lining. An entirely artificial channel should be qualified with the \"canal\" or \"ditch\" secondary site type.",
  "ST-CA", "Canal", "An artificial watercourse designed for navigation, drainage, or irrigation by connecting two or more bodies of water; it is larger than a ditch.",
  "ST-DCH", "Ditch", "An excavation artificially dug in the ground, either lined or unlined, for conveying water for drainage or irrigation; it is smaller than a canal.",
  "ST-TS", "Tidal stream", "A stream reach where the flow is influenced by the tide, but where the water chemistry is not normally influenced. A site where ocean water typically mixes with stream water should be coded as an estuary.",
  "WE", "Wetland", "Land where saturation with water is the dominant factor determining the nature of soil development and the types of plant and animal communities living in the soil and on its surface (Cowardin, December 1979). Wetlands are found from the tundra to the tropics and on every continent except Antarctica. Wetlands are areas that are inundated or saturated by surface or groundwater at a frequency and duration sufficient to support, and that under normal circumstances do support, a prevalence of vegetation typically adapted for life in saturated soil conditions. Wetlands generally include swamps, marshes, bogs and similar areas. Wetlands may be forested or unforested, and naturally or artificially created."
  )

```

```{r 12_export_data}

write_csv(discharge, "data/discharge_daily_06445980.csv")
write_csv(meta_avail_data, "data/meta_avail_data_06445980.csv")
write_csv(meta_NWIS_site_codes, "data/meta_NWIS_site_codes.csv")
write_csv(meta_NWIS_site_types, "data/meta_NWIS_site_types.csv")
write_csv(meta_peak_discharge_codes, "data/meta_cds_peak_discharge.csv")
write_csv(meta_peak_gage_ht_codes, "data/meta_cds_peak_gage_ht.csv")
write_csv(meta_peak_vars, "data/meta_cds_peak_vars.csv")

write_csv(peakData, "data/discharge_peak_06445980.csv")
write_csv(siteINFO, "data/meta_site_06445980.csv")

write_csv(sites, "data/sites_in_bb.csv")
write_csv(sites_peak, "data/sites_peak_in_bb.csv")
write_csv(what_data, "data/what_data_in_bb.csv")

write_csv(gage_ht_87_99, "data_output/gage-ht_06445980_87-99.csv")

#write_csv(param_codes, "data/meta_cds_param.csv")




```

