---
title: "Peak flow locs for Northwestern Great Plains and High Plains ecoregion"
author: "CJ Tinant"
date: "`r Sys.Date()`"
output: html_document
---

<!--
Gets all USGS site numbers from a bounding box
Filters by stream, peak flow
-->

```{r 00_setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# library
library(tidyverse)        # Load the 'Tidyverse' packages: ggplot2, dplyr, 
                          #   tidyr, readr, purrr, tibble, stringr, and forcats
library(dataRetrieval)    # Retrieval functions for USGS and EPA hydrology and
                          #   water quality data
library(sf)               # Simple features for R
library(here)

```

```{r 01_get_peak_flow_sites}

# Get peak flow sites in the Northern Great Plains and High Plains bb
sites_nw <- whatNWISsites(                     #  xmin   ymin  xmax  ymax
  bBox = c(-112, 43.8, -105, 48.6)             #  west  south  east  north
  )

sites_ne <- whatNWISsites(
  bBox = c(-105, 43.8, -98.9, 48.6)
  )

sites_ncw <- whatNWISsites(                     #  xmin   ymin  xmax  ymax
  bBox = c(-112, 39.2, -105, 43.8)              #  west  south  east  north
  )

sites_nce <- whatNWISsites(
  bBox = c(-105, 39.2, -98.9, 43.8)
  )

sites_scw <- whatNWISsites(                     #  xmin   ymin  xmax  ymax
  bBox = c(-112, 35.6, -105, 39.2)              #  west  south  east  north
  )

sites_sce <- whatNWISsites(
  bBox = c(-105, 35.6, -98.9, 39.2)
  )

sites_sw <- whatNWISsites(                     #  xmin   ymin  xmax  ymax
  bBox = c(-112, 31.6, -105, 35.6)              #  west  south  east  north
  )

sites_se <- whatNWISsites(
  bBox = c(-105, 31.6, -98.9, 35.6)
  )

sites_sa <- whatNWISsites(
  bBox = c(-112, 31.2, -98.9, 31.6)
  )

# bind rows -all sites
sites_all <- bind_rows(sites_nw, sites_ne,
                       sites_ncw, sites_nce,
                       sites_scw, sites_sce,
                       sites_sw, sites_se,
                       sites_sa)

#sites_all_n <- bind_rows(sites_nw, sites_ne,
#                       sites_ncw, sites_nce)

#sites_all_s <- bind_rows(sites_scw, sites_sce,
#                       sites_sw, sites_se,
#                       sites_sa)

# clean up Global Environment
rm(list = ls(pattern = "sites_n"))
rm(list = ls(pattern = "sites_s"))

```

```{r 02_filter_peak-flow_sites}
# get a list of all streamflow flow data in bounding box
sites_st <-sites_all %>%
  filter(site_tp_cd == "ST")

# get all peak flow data in bounding box
sites_pk <-  whatNWISdata(
  siteNumber = sites_st$site_no,
  service = "pk"
  )

# convert stations into a spatial format (sf) object
sites_peak <- st_as_sf(sites_pk,
                    coords = c("dec_long_va",        # note x goes first
                                "dec_lat_va"),
                    crs = 4269,                     # projection, this is NAD83
                    remove = FALSE)                 # don't remove lat/lon cols
```

```{r 03_import_eco_shapefile}

# load sites peak metadata
#sites <- read_csv("data/sites_peak.csv")

# load ecoregion shapefile
eco_l3 <- st_read("data_spatial/data_spus_eco_l3/us_eco_l3.shp") %>%
  janitor::clean_names()

# explore names
eco_l1_names <- eco_l3 %>%
  as.data.frame() %>%
  select(na_l1name) %>%
  distinct()

eco_l2_names <- eco_l3 %>%
  as.data.frame() %>%
  filter(na_l1name == "GREAT PLAINS" |
         na_l1name == "SOUTHERN SEMI-ARID HIGHLANDS") %>%
  select(na_l2name) %>%
  distinct()
  
eco_l3_na_names <- eco_l3 %>%
  as.data.frame() %>%
  filter(na_l2name == "WEST-CENTRAL SEMI-ARID PRAIRIES" |
         na_l2name == "SOUTH CENTRAL SEMI-ARID PRAIRIES") %>%
  select(na_l3name) %>%
  distinct()
```

```{r 04_reproject_eco_shapefile}

# check geometry
crs_eco_l3 <- eco_l3 %>%
  st_crs()

# subset study area -- Albers refers to Albers Equal Area Conic projection
study_area_albers <- eco_l3 %>%
  filter(na_l3name == "High Plains" |
         na_l3name == "Northwestern Great Plains")

# project study area to NAD83 Geographic (ESPG:4269)
study_area_unproj <- study_area_albers %>%
  st_transform(crs = 4269)

crs_study_area_unproj <- study_area_unproj %>%
  st_crs()

# make bounding box
bb_study_area_unproj <- study_area_unproj %>%
  st_bbox() %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  pivot_longer(-rowname) %>%
  pivot_wider(names_from = rowname,
              values_from = value) %>%
  select(-name) %>%
  mutate(delta_x = xmax - xmin) %>%
  mutate(delta_y = ymax - ymin)

# clean up Global Environment
rm(list = ls(pattern = "names"))
rm(list = ls(pattern = "crs"))
rm(eco_l3)

```

```{r 05_intersect_sites_study_area}

#out <- st_intersection(points, poly)
sites_peak <- st_intersection(sites_peak_all, study_area_unproj)

# plot results
ggplot() +
  geom_sf(data = study_area_unproj) +
  geom_sf(data = sites_peak,
          size = 0.5)
```

```{r 06_drop_cols_export_result}

sites_peak <- sites_peak %>%
  select(
    # no variance among station values
    -c(
      agency_cd,        # all = USGS
      site_tp_cd,       # all = ST
      data_type_cd,     # all = pk
      parm_cd,          # all = NA
      stat_cd,          # all = NA
      ts_id,            # all = 0
      loc_web_ds,       # all = NA
      medium_grp_cd,    # all = wat
      parm_grp_cd,      # all = ST
      srs_id,           # all = 0
      access_cd,        # all = 0
      # non-important vars
      alt_acy_va,
      coord_acy_cd,
      # not-needed ecoreg names
      na_l3code,
      na_l3name,
      na_l2code,
      na_l2name,
      na_l1code,
      na_l1name,
      l3_key,
      l2_key,
      l1_key,
      shape_leng,
      shape_area
    ))

# save as a csv
write_csv(sites_peak, "data/sites_peak.csv")

# clean up Global Environment
rm(list = ls(pattern = "sites"))
rm(list = ls(pattern = "study"))

```


<!--

# Ecoregion hierarchy
Northwestern Great Plains and High Plains region of the SOUTH CENTRAL SEMI-ARID PRAIRIES of the GREAT PLAINS ecoregion

## Next steps
create an inline unzip
unzip /path/to/your/file.zip -d /path/to/destination/folder

-- need to add ecoreg when joining

* intersect level 3 ecoregion with station data
* sync personal and group Zotero library for FFA
https://guides.library.oregonstate.edu/c.php?g=359201&p=2426111
https://www.zotero.org/groups/5473862/olc_flood-frequency


## Helpful references:
GIT issues--
[GIT issues](https://dangitgit.com/)

Spatial data issues--
[Intro to spatial data in R](https://www.r4wrds.com/intro/m_intro_mapmaking)
[Overview of Coordinate Reference Systems (CRS) in R](https://www.nceas.ucsb.edu/sites/default/files/2020-04/OverviewCoordinateReferenceSystems.pdf)
[Geocomputation with R](https://r.geocompx.org/)

--> 


