---
title: "Get peak flow data for Northwestern Great Plains ecoregion gages"
author: "CJ Tinant"
date: "`r Sys.Date()`"
output: html_document
---

<!--



## Next steps
* shapefile to sp class for level 3 ecoregion
* intersect level 3 ecoregion with station data
* sync personal and group Zotero library for FFA
https://guides.library.oregonstate.edu/c.php?g=359201&p=2426111
https://www.zotero.org/groups/5473862/olc_flood-frequency


## Helpful references:
GIT issues--
[GIT issues](https://dangitgit.com/)

Spatial data issues--
[Intro to spatial data in R](https://www.r4wrds.com/intro/m_intro_mapmaking)
[Overview of Coordinate Reference Systems (CRS) in R](https://www.nceas.ucsb.edu/sites/default/files/2020-04/OverviewCoordinateReferenceSystems.pdf)
[Geocomputation with R](https://r.geocompx.org/)

--> 

```{r 00_setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# library
library(tidyverse)        # Load the 'Tidyverse' packages: ggplot2, dplyr, 
                          #   tidyr, readr, purrr, tibble, stringr, and forcats
library(dataRetrieval)    # Retrieval functions for USGS and EPA hydrology and
                          #   water quality data
library(sf)               # Simple features for R

```

```{r 01_import_sites_meta_eco_shapefile, eval=FALSE}
# load sites peak metadata
sites_peak <- read_csv("data/sites_peak.csv")

# load ecoregion shapefile
eco_l3 <- st_read("data_spatial/data_spus_eco_l3/us_eco_l3.shp") %>%
  janitor::clean_names()

# explore names
eco_l1_names <- eco_l3 %>%
  as.data.frame() %>%
  select(na_l1name) %>%
  distinct()

eco_l2_names <- eco_l3 %>%
  as.data.frame() %>%
  filter(na_l1name == "GREAT PLAINS" |
         na_l1name == "SOUTHERN SEMI-ARID HIGHLANDS") %>%
  select(na_l2name) %>%
  distinct()
  
eco_l3_na_names <- eco_l3 %>%
  as.data.frame() %>%
  filter(na_l2name == "WEST-CENTRAL SEMI-ARID PRAIRIES" |
         na_l2name == "SOUTH CENTRAL SEMI-ARID PRAIRIES") %>%
  select(na_l3name) %>%
  distinct()
```

```{r 02_check_eco_shapefile, eval=FALSE}
# subset study area
study_area <- eco_l3 %>%
  filter(na_l3name == "High Plains" |
         na_l3name == "Northwestern Great Plains") 

# check geometry
study_area$geometry

# project geometry into NAD83
study_area <- st_transform(study_area,
                     crs = 4269)

study_area$geometry

# clean up global environment
rm(list = ls(pattern = "eco"))

```



```{r things, eval=FALSE}



test <- st_join(sites_gt_20, study_area)

```


```{r 03_imake_peak_sites_spatial}

# convert_df_to_spatial_format--
# get datum 
datum <- sites_gt_20 %>%
  select(dec_coord_datum_cd) %>%
  distinct()

datum_sites <- datum$dec_coord_datum_cd

# convert stations into a spatial format (sf) object
sites_gt_20 <- st_as_sf(sites_gt_20,
                    coords = c("dec_long_va",        # note x goes first
                                "dec_lat_va"),
                    crs = 4269,                     # projection, this is NAD83
                    remove = FALSE)                 # don't remove lat/lon cols

# clean up Global Environment
rm(list = ls(pattern = "datum"))

# quick plot of the geometry
plot(sites_gt_20,
     max.plot = 14)

```

```{r}

# subset sites gt 20
sites_gt_20 <- sites_peak %>%
  filter(count_nu >= 20)

# remove not-needed data
sites_gt_20 <- sites_gt_20 %>%
  select(
    # no variance among station values
    -c(agency_cd,                 # all = USGS
       site_tp_cd,                # all = ST
       data_type_cd,              # all = pk
       parm_cd,                   # all = NA
       stat_cd,                   # all = NA
       ts_id,                     # all = 0
       loc_web_ds,                # all = NA
       medium_grp_cd,             # all = wat
       parm_grp_cd,               # all = ST
       srs_id,                    # all = 0
       access_cd,                 # all = 0
    # non-important vars
       alt_acy_va,
       coord_acy_cd
    )) 

```

```{r 02_import_munge_peak_sites}

# get site data
sites <- read_csv("data/sites_peak.csv")

# convert_df_to_spatial_format--
# get datum 
datum <- sites %>%
  select(dec_coord_datum_cd) %>%
  distinct()

datum_sites <- datum$dec_coord_datum_cd

# convert stations into a spatial format (sf) object
sites <- st_as_sf(sites,
                    coords = c("dec_long_va",        # note x goes first
                                "dec_lat_va"),
                    crs = 4269,                     # projection, this is NAD83
                    remove = FALSE)                 # don't remove lat/lon cols

# clean up Global Environment
rm(list = ls(pattern = "datum"))

```

```{r 01_make_site_criteria_code}

# quick plot of the geometry
#plot(sites,
#     max.plot = 14)


site_criteria_cde <- tribble(
    ~code, ~description,
    "agency_cd", "The agency that is reporting the data. Agency codes are fixed values assigned by the National Water Information System (NWIS).",
  "site_no", "Each site in the USGS data base has a unique 8- to 15-digit identification number.",
  "station_nm", "This is the official name of the site in the database. For well information this can be a district-assigned local number.",
 "site_tp_cd", "A list of primary and secondary site types that can be associated with data collection sites. A site type is a generalized location in the hydrologic cycle, or a man-made feature thought to affect the hydrologic conditions measured at a site. All sites are associated with a primary site type, and may additionally be associated with a secondary site type that further describes the location.",
 "dec_lat_va", "Latitude in decimal degrees",
 "dec_long_va", "Longitude in decimal degrees",
 "coord_acy_cd", "Lat/Long coordinate accuracy codes indicating the accuracy of the latitude longitude values.",
 "dec_coord_datum_cd", "Lat/Long coordinate datum.",
 "alt_va", "Altitude of the site referenced to the specified Vertical Datum",
 "alt_acy_va", "Altitude accuracy value. Many altitudes are interpolated from the contours on topographic maps; accuracies determined in this way are generally entered as one-half of the contour interval.",
 "alt_datum_cd", "Altitude coordinate datum.",
 "huc_cd", "Hydrologic unit codes. The United States is divided and sub-divided into successively smaller hydrologic units which are classified into four levels: regions, sub-regions, accounting units, and cataloging units. The hydrologic units are arranged within each other, from the smallest (cataloging units) to the largest (regions). Each hydrologic unit is identified by a unique hydrologic unit code (HUC) consisting of two to eight digits based on the four levels of classification in the hydrologic unit system.",
 "data_type_cd", "All USGS data falls into one of: Current Conditions, Daily Data, Surface Water, Water Quality, Groundwater. Current condition data is any data down to the 15 minute interval that has been transmitted in the last 120 days. Daily Data is the average daily value for a site. Surface Water is water flow and levels in streams, lakes and springs. Water Quality is chemical and physical data for streams, lakes, springs, and wells. Groundwater is water levels in wells.",
 "parm_cd", "Parameter code",
 "stat_cd", "Statistics code",
 "ts_id", "",
 "loc_web_ds", "",
 "medium_grp_cd", "Medium type refers to the specific environmental medium that was sampled and analyzed. Medium type differs from site type because one site type, such as surface water, could have data for several media, such as water, bottom sediment, fish tissue, and others.",
 "parm_grp_cd", "Parameter group code",
 "srs_id", "USEPA SRS.http://www.epa.gov/srs/",
 "access_cd", "",
 "begin_date", "Begin date of the period of record for the data",
 "end_date", "End date of the period of record for the data",
 "count_nu", "Number of records",
 "ecoreg", ""
 )

```

