---
title: "Peak flow locs for Northwestern Great Plains and High Plains ecoregion"
author: "CJ Tinant"
date: "`r Sys.Date()`"
output: html_document
---

<!--
PURPOSE: prepare peak flow data for analysis.

METHODS:
This code chunk cleans peak flow data and metadata

DATA DICTIONARY
peak_data_orig -- original peak flow records
peak_date_miss -- peak flow records missing dates
peak_data      -- working peak flow records
peak_flag_summ -- USGS codes for data flags
peak_flags     -- peak flow records with flags
sites_peak     -- peak flow station metadata

-->

```{r 00_setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# library
library(tidyverse)        # Load the 'Tidyverse' packages: ggplot2, dplyr, 
                          #   tidyr, readr, purrr, tibble, stringr, and forcats
library(dataRetrieval)    # Retrieval functions for USGS and EPA hydrology and
                          #   water quality data
library(sf)               # Simple features for R
library(Lmoments)         # L-moments and trimmed L-moments from the data
library(lmom)

```

```{r 01_import_peak-flow_pf-data_pf-station-metadata}

# get peakflow metadata
sites_peak <- read_csv("data/sites_peak.csv")

# get peakflow data
peak_data_orig <- read_csv("data/data_peak.csv")

```

```{r 02_make_pf-flag-descriptions}

pead_flag_desc <- tribble(
  ~peak_cd, ~peak_cd_descr,
  "1", "Discharge is a Maximum Daily Average",
  "2", "Discharge is an Estimate",
  "3", "Discharge affected by Dam Failure",
  "4", "Discharge less than indicated value which is Minimum Recordable Discharge at this site",
  "5", "Discharge affected to unknown degree by Regulation or Diversion",
  "6", "Discharge affected by Regulation or Diversion",
  "7", "Discharge is an Historic Peak",
  "8", "Discharge actually greater than indicated value",
  "9", "Discharge due to Snowmelt, Hurricane, Ice-Jam or Debris Dam breakup",
  "A", "Year of occurrence is unknown or not exact",
  "Bd", "Day of occurrence is unknown or not exact",
  "Bm", "Month of occurrence is unknown or not exact",
  "C", "All or part of the record affected by Urbanization, Mining, Agricultural changes, Channelization, or other",
  "F", "Peak supplied by another agency",
  "O", "Opportunistic value not from systematic data collection",
  "R", "Revised"
  )

```

```{r 03_pf_data_check_flags}

# tidy data flags
#   peak_flags    
peak_flags <- peak_data_orig %>%
  select(-peak_va) %>%
  distinct() %>%
  filter(!is.na(peak_cd)) %>%
  separate(peak_cd, into = c("scratch_1",
                             "scratch_2",
                             "scratch_3",
                             "scratch_4",
                             "scratch_5"
                             ),
           sep = ",",
           remove = FALSE,
           extra = "merge") %>%
  pivot_longer(cols = starts_with("scratch")) %>%
  select(-c(peak_cd, name)) %>%
  rename(peak_cd = value) %>%
  distinct() %>%
  filter(!is.na(peak_cd))

peak_flag_summ <- peak_flags %>%
  select(peak_cd) %>%
  distinct() %>%
  arrange(peak_cd)

```

```{r 04_pf_data_check_dates}

# separate missing dates for recheck

# get missing peak flow dates
peak_date_miss <- peak_data_orig %>%
  filter(is.na(peak_dt))

peak_data <- anti_join(peak_data_orig, peak_date_miss)

```


# revise below
```{r 04_pf_data_get_peak_months}

peak_months <- peak_data %>%
  mutate(peak_mon = month(peak_dt)
         ) %>%
  select(c(peak_dt, site_no, peak_mon))

peak_mon_ck <- peak_months %>%
  filter(is.na(peak_mon))



  group_by(site_no) %>%
  summarise(mon_mean = mean(peak_mon),
            mon_median = median(peak_mon),
            mon_sd = sd(peak_mon)
             ) %>%
  ungroup()

```

```{r 02_munge_pf_data_drop_vars, eval=FALSE}

# drop not needed vars

peak_data <- peak_data %>%
  select(-c(
    agency_cd,
    peak_tm,
    gage_ht,
    gage_ht_cd,
    ag_tm,
    ag_gage_ht,
    ag_gage_ht_cd,
    peak_dateTime,
    ag_dateTime,
    ag_dt,
    year_last_pk
  ))

```

```{r 04_munge_pf_metadata}

# Identify missing data
sites_gt_20_missing_data <- sites_peak %>%
  summarize(across(everything(), ~sum(is.na(.)))) %>%
  pivot_longer(cols = everything())

```



```{r fix_this_how_to_get_Lmoments}

moments <- peak_data %>%
  group_by(site_no) %>%
  samlmu(peak_data$peak_va, 4)

  summarise(moments = Lmoments(peak_data$peak_va))


```


<!--
# Ecoregion hierarchy
Northwestern Great Plains and High Plains region of the SOUTH CENTRAL SEMI-ARID PRAIRIES of the GREAT PLAINS ecoregion

## Next steps
create an inline unzip
unzip /path/to/your/file.zip -d /path/to/destination/folder

-- need to add ecoreg when joining


* sync personal and group Zotero library for FFA
https://guides.library.oregonstate.edu/c.php?g=359201&p=2426111
https://www.zotero.org/groups/5473862/olc_flood-frequency


## Helpful references:
GIT issues--
[GIT issues](https://dangitgit.com/)

Spatial data issues--
[Intro to spatial data in R](https://www.r4wrds.com/intro/m_intro_mapmaking)
[Overview of Coordinate Reference Systems (CRS) in R](https://www.nceas.ucsb.edu/sites/default/files/2020-04/OverviewCoordinateReferenceSystems.pdf)
[Geocomputation with R](https://r.geocompx.org/)

References:
[dataRetrieval tutorial](https://waterdata.usgs.gov/blog/dataretrieval/)

[USGS watermapper](https://maps.waterdata.usgs.gov/mapper/index.html)
-->






