---
title: "Regional skew coefficient analysis "
subtitle: "Clean data
author: "CJ Tinant"
date: "`r Sys.Date()`"
output: html_document
---

<!--
Purpose: Iteratively visualize and select ecoregions for AOI

Overview:
* load and process spatial data -- currently only locally works
-- imports and validates shapefiles
-- returns spatial objects with centroid and coordinates

* iteratively visualize and select ecoregions for AOI

* export results

# Next steps:
* fix CyVerse to work with the data

# References:
https://github.com/EmilHvitfeldt/r-color-palettes
https://r.geocompx.org/
-->

```{r 00_setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

# library
library(tidyverse)        # Load the 'Tidyverse' packages: ggplot2, dplyr, 
                          #   tidyr, readr, purrr, tibble, stringr, and forcats
library(dataRetrieval)    # Retrieval functions for USGS and EPA hydrology and
                          #   water quality data
library(sf)               # Simple features for R
library(here)



```

## Get data -- either from Cyverse or locally
```{r 01a_get_and_clean_data_local}

# load shapefiles -- local path -- and check geometry
file_path <- "data_spatial/"

# usa ecoregions level 3
file_name <- "us_eco_l3/us_eco_l3.shp"
eco_l3 <- st_read(paste(file_path,
                        file_name,
                        sep = "")) %>%
  janitor::clean_names() %>%
  process_geometries()

# usa states
file_name <- "tl_2012_us_state/tl_2012_us_state.shp"
state_bdy_usa <- st_read(paste(file_path,
                        file_name,
                        sep = "")) %>%
  janitor::clean_names() %>%
  process_geometries()

# usa tribal lands
file_name <- "tl_2020_us_aitsn/tl_2020_us_aitsn.shp"
tribal_lands_usa <- st_read(paste(file_path,
                        file_name,
                        sep = "")) %>%
  janitor::clean_names() %>%
  process_geometries()

# census codes for American Indian, Alaska Native, and
#   Native Hawaiian Areas (AIANNH) 2020 ----
#     https://www.census.gov/library/reference/code-lists/ansi.html
#   need to pivot the data because tribal lands in multiple states
file_path <- "data_spatial/metadata/"
file_name <- "national_aiannh2020.csv"

aiannh_table <- read_csv(paste(file_path, file_name, sep = "")) %>%
  janitor::clean_names()

# clean up Global Environment
rm(list = ls(pattern = "file"))
rm(list = ls(pattern = "process"))

```

```{r 01b_get_and_clean_data_Cyverse, eval=FALSE}

# load shapefiles -- local path -- and check geometry
eco_l3 <- st_read("data_spatial/us_eco_l3/us_eco_l3.shp") %>%
  janitor::clean_names() %>%
  process_geometries()

eco_l4 <- st_read("data_spatial/us_eco_l4/us_eco_l4_no_st.shp") %>%
  janitor::clean_names() %>%
  process_geometries()

state_bdy <- st_read("data_spatial/tl_2012_us_state/tl_2012_us_state.shp") %>%
  janitor::clean_names() %>%
  process_geometries()

tribal_lands_usa <- st_read("data_spatial/tl_2020_us_aitsn/tl_2020_us_aitsn.shp") %>%
  janitor::clean_names() %>%
  process_geometries()

# load 2020 Census codes for American Indian, Alaska Native, and
#   Native Hawaiian Areas (AIANNH)----
#     https://www.census.gov/library/reference/code-lists/ansi.html
#   need to pivot the data because tribal lands in multiple states
file_path <- "data_spatial/metadata/"
file_name <- "national_aiannh2020.csv"

aiannh_table <- read_csv(paste(file_path, file_name, sep = "")) %>%
  janitor::clean_names() #%>%

aiannh_table_long <- aiannh_table %>%
  separate_wider_delim(
    cols = states,
    delim = "~",
    names = c("scratch_1", "scratch_2", "scratch_3"),
    too_few = "align_start",
    too_many = "merge"
    ) %>%
  pivot_longer(cols = starts_with("scratch"),
               names_to = "scratch",
               values_to = "states") %>%
  select(-scratch) %>%
  filter(!is.na(states))

```

```{r}

ggplot() +
   geom_sf(data = tribal_lands_usa,
            fill = "gray50",
            alpha = 0.5
#           aes(fill = aiannhce,
#           show.legend = FALSE)
           ) +
coord_sf(xlim = c(-100, -95), ylim = c(40, 45))  # Set the limits for longitude and latitude


```


```{r}

# select the census codes for states in Rocky Mountain and Great Plains regions
aiannh2 <- aiannh_table %>%
  filter(states == "SD" |
         states == "ND" |
         states == "NE" |
         states == "MT" |
         states == "WY"
           )

joined_data <- tribal_lands_usa %>%
  right_join(aiannh2, by = "aiannhce")

```






## Visualize ecoregions and select study area

```{r 02a_intersect_eco_l3_bdry_w_rm_gp_region}

# This code chunk intersects eco_l3 with the RM and GP region boundary for
#   Indian Lands of Federally Recognized Tribes of the United States
#   1. filter the tribal lands in Rocky Mountain and Great Plains regions
#         start with selecting census codes for states in RM and GP ecoregions;
#   2. check shapefiles geometry
#   3. Reproject ecoregion shapefile to NAD83 Geographic (ESPG:4269) -- Lat Lon
#   4. Filter States in Rocky Mountain and Great Plains regions
#   5. Make a single polygon of the Rocky Mountain and Great Plains regions

# select the census codes for states in Rocky Mountain and Great Plains regions
aiannh_rm_gp <- aiannh_table %>%
  filter(states == "SD" |
         states == "ND" |
         states == "NE" |
         states == "MT" |
         states == "WY"
           )

joined_data <- tribal_lands_usa %>%
  left_join(aiannh_rm_gp, by = "aiannhce")

# filter the tribal lands in Rocky Mountain and Great Plains regions
tribal_lands_rm_gp <- tribal_lands_usa %>%
  filter(aiannhce %in% aiannh_rm_gp$aiannhce)

# check geometry of shapefiles
crs_geom_eco <- eco_l3 %>%
  st_crs() %>%
  pluck(.,1)

crs_geom_st_bdy_usa <- state_bdy_usa %>%
  st_crs() %>%
  pluck(.,1)

# reproject ecoregions to NAD83 Geographic (ESPG:4269) -- Lat Lon
eco_l3_proj <- eco_l3 %>%
  st_transform(crs = 4269)

# filter States in Rocky Mountain and Great Plains regions
state_bdy <- state_bdy_usa %>%
  filter(stusps == "SD" |
         stusps == "ND" |
         stusps == "NE" |
         stusps == "MT" |
         stusps == "WY"
           )

# make a single polygon of the Rocky Mountain and Great Plains regions
# https://mgimond.github.io/Spatial/vector-operations-in-r.html
rm_gp_bdy <- state_bdy %>%
  st_union(.,
           by_feature = FALSE)

# make polygons of aiannh
tribal_lands <- tribal_lands_rm_gp %>%
  st_union(.,
           by_feature = FALSE)

# intersect eco_l3 by the Rocky Mountain and Great Plains region boundary
eco_l3_rm_gp <- st_intersection(eco_l3_proj, rm_gp_bdy)

# clean up Global Environment
rm(aiannh_table,
   eco_l3_proj,
   eco_l3,
   state_bdy_usa,
#   tribal_lands_usa,
   crs_geom_eco,
   crs_geom_st_bdy_usa
   )



```

```{r}

ggplot() +
   geom_sf(data = tribal_lands_usa,
            fill = "gray50",
            alpha = 0.5
#           aes(fill = aiannhce,
#           show.legend = FALSE)
           )

```


```{r 02b_visualize_eco_l3_bdry_w_rm_gp_region}

# orig data
# make a quick plot
# ggplot() +
#   geom_sf(data = eco_l3_rm_gp,
#           aes(fill = us_l3name,)) +
#   geom_sf(data = state_bdy,
#           fill = "transparent")

# cleaner theme
ggplot() +
  geom_sf(data = eco_l3_rm_gp,    # Fill regions based on ecological names
          aes(fill = us_l3name)
          ) +  
  geom_sf(data = state_bdy,       # State boundaries with no fill
          fill = NA,
          color = "black",
          size = 0.5
          ) +
   geom_sf(data = tribal_lands_usa,
            fill = "gray50",
            alpha = 0.5
#           aes(fill = aiannhce,
#           show.legend = FALSE)
           ) +
  labs(title = "Ecological Regions with State Boundaries",
       fill = "Ecological Region") +  # Adding title and legend title
  scale_fill_viridis_d() +  # A color scale that's visually appealing and accessible
  theme_minimal()  # A clean theme

```

```{r 02c_visually_explore_l1_great-plains}

# Select the Great Plains Level 1 ecoregion
eco_l3_gp <- eco_l3_rm_gp %>%
  filter(na_l1name == "GREAT PLAINS")

# Plot with text labels
# ggplot() +
#   geom_sf(data = eco_l3_gp,
#           aes(fill = us_l3name)) +
#   geom_sf(data = state_bdy,
#           fill = "transparent")

# cleaner theme
ggplot() +
  geom_sf(data = eco_l3_gp,    # Fill regions based on ecological names
          aes(fill = us_l3name)
          ) +  
  geom_sf(data = state_bdy,       # State boundaries with no fill
          fill = NA,
          color = "black",
          size = 0.5
          ) +
   geom_sf(data = tribal_lands,
            fill = "gray50",
            alpha = 0.5
#           aes(fill = aiannhce,
#           show.legend = FALSE)
           ) +
  labs(title = "Great Plains Ecoregions with State Boundaries",
       fill = "Ecological Region") +  # Adding title and legend title
  scale_fill_viridis_d() +  # A color scale that's visually appealing and accessible
  theme_minimal()  # A clean theme

```

```{r 02d_visually_explore_l2_semi-arid-prairies}

# Select the Great Plains Level 1 ecoregion
eco_l3_semi <- eco_l3_rm_gp %>%
  filter(na_l2name == "SOUTH CENTRAL SEMI-ARID PRAIRIES" |
         na_l2name == "WEST-CENTRAL SEMI-ARID PRAIRIES")

# Plot with text labels
# ggplot() +
#   geom_sf(data = eco_l3_semi,
#           aes(fill = us_l3name)) +
#   geom_sf(data = state_bdy,
#           fill = "transparent") +
#   geom_sf(data = tribal_lands_rm_gp,
#           aes(fill = aiannhce),
#           show.legend = c(fill = FALSE))

# cleaner theme
ggplot() +
  geom_sf(data = eco_l3_semi,    # Fill regions based on ecological names
          aes(fill = us_l3name)
          ) +  
  geom_sf(data = state_bdy,       # State boundaries with no fill
          fill = NA,
          color = "black",
          size = 0.5
          ) +
   geom_sf(data = tribal_lands,
            fill = "gray50",
            alpha = 0.5
#           aes(fill = aiannhce,
#           show.legend = FALSE)
           ) +
  labs(title = "Semi-Arid Great Plains Ecoregions with State Boundaries",
       fill = "Ecological Region") +  # Adding title and legend title
  scale_fill_viridis_d() +  # A color scale that's visually appealing and accessible
  theme_minimal()  # A clean theme

```

```{r 02e_visually_explore_l3_semi-arid-prairies_not_glaciated}

# Select the Great Plains Level 1 ecoregion
eco_l3_semi_ng <- eco_l3_semi %>%
  filter(na_l3name != "Northwestern Glaciated Plains")

# # Plot with text labels
# ggplot() +
#   geom_sf(data = eco_l3_semi_ng,
#           aes(fill = us_l3name,
#               show.legend = FALSE)
#           ) +
#   geom_sf(data = state_bdy,
#           fill = "transparent") +
#   geom_sf(data = tribal_lands_rm_gp,
#           alpha = 0.5) +
#   theme_minimal() +
#   ggtitle("Map of level-3 ecoregions") 

# cleaner theme
ggplot() +
  geom_sf(data = eco_l3_semi_ng,    # Fill regions based on ecological names
          aes(fill = us_l3name)
          ) +  
  geom_sf(data = state_bdy,       # State boundaries with no fill
          fill = NA,
          color = "black",
          size = 0.5
          ) +
  labs(title = "Non-glaciated Semi-Arid Great Plains Ecoregions",
       fill = "Ecological Region") +  # Adding title and legend title
  scale_fill_viridis_d() +  # A color scale that's visually appealing and accessible
  theme_minimal()  # A clean theme

```


